### ISSUE TITLE
Compiler message: file:///Users/xxx/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.2.0/lib/src/builder.dart:326:49: Error: The getter 'children' isn't defined for the class 'InlineSpan'.  - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('file:///Users/xxx/flutter/packages/flutter/lib/src/painting/inline_span.dart'). Try correcting the name to the name of an existing getter, or defining a getter or field named 'children'.         List<TextSpan> children = previous.text.children != null                                                 ^^^^^^^^

### ISSUE THREAD

**Issue by calvinmuller** [flutter/flutter_markdown#103]
Compiler message:
file:///Users/calvinmuller/.pub-cache/hosted/pub.dartlang.org/flutter_markdown-0.2.0/lib/src/builder.dart:326:49: Error: The getter 'children' isn't defined for the class 'InlineSpan'.
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('file:///Users/calvinmuller/iStreet/Mobile/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'children'.
        List<TextSpan> children = previous.text.children != null
                                                ^^^^^^^^

```
[✓] Flutter (Channel master, v1.7.2-pre.30, on Mac OS X 10.14.4 18E226, locale en-ZA)
    • Flutter version 1.7.2-pre.30 at /Users/calvinmuller/iStreet/Mobile/flutter
    • Framework revision 14414f350a (8 hours ago), 2019-06-05 18:14:17 -0700
    • Engine revision 3371da1e09
    • Dart version 2.3.2 (build 2.3.2-dev.0.1 9dcb026b26)
```

**Comment by rohanchandra** [comment]
There's a breaking change in Flutter master at the moment (see PR #102).

In the meantime, I'm using a hotfix branch in my own app:

```yaml
dependencies:
  flutter_markdown:
    git:
      url: https://github.com/rohanchandra/flutter_markdown
      ref: new-inlinespan-api
```

Alternatively, you can use a stable or dev version of Flutter.

**Comment by rohanchandra** [comment]
The fix has landed in master, so you shouldn't have this issue anymore.
