### ISSUE TITLE
Center markdown vertically

### ISSUE THREAD

**Issue by strudelbeast** [flutter/flutter_markdown#109]
Heyy,

Is there a possibility to Center the Markdown vertically in a Container if there is not enough text that you can scroll?

![image](https://user-images.githubusercontent.com/22666594/62426580-d5f75400-b6e6-11e9-86b1-aa35bbce04a0.png)

In this example the text should be positioned at the yellow box

Thanks in advance.

**Comment by IchordeDionysos** [comment]
Are you using `Markdown` or `MarkdownBody`?
Does it help if you wrap `MarkdownBody` with a `Center` widget and if you want scrolling wrap `Center` in a `SingleChildScrollView` like this:

```dart
SingleChildScrollView(
  child: Center(
    child: MarkdownBody(
      data: "Markdown",
    ),
  ),
);
```
