### ISSUE TITLE
incorrect bottom padding in <pre>

### ISSUE THREAD

**Issue by namiwang** [flutter/flutter_markdown#126]
# repro case

~~~
```
line 1
line 2
line 3
line 4
```
~~~

# actually

![Screen Shot 2019-09-19 at 14 31 14](https://user-images.githubusercontent.com/1160688/65218962-2a656000-daea-11e9-93e8-163990897431.png)

# expected

proper bottom padding

# research

Not sure if this is about a suffix \n or wrong bottom padding

**Comment by KagurazakaHanabi** [comment]
Maybe about a suffix \n
