### ISSUE TITLE
Issues displaying any sort of image with Markdown.imageBuilder

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter_markdown#139]
flutter_markdown version: 0.3.0
Anytime I use `imageBuilder` to display an image, I get the exception:

`Exception: Could not instantiate image codec.`

Minimal code reproducing the error: https://github.com/ThinkDigitalSoftware/svg_cache_example

The gist of it is:
```dart
Markdown(
                data:
                    '![svg image](https://api.travis-ci.org/rrousselGit/provider.svg?branch=master)',
                imageBuilder: (uri) {
                  return Column(
                    children: <Widget>[
                      Image.network(// regular image
                          'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png'),
                      SvgPicture.network(uri.toString()) //  svg Image
                    ],
                  );
                },
              ),
            )
```

**Comment by ThinkDigitalSoftware** [comment]
Also, when setting a breakpoint in the `imageBuilder` callback, It never seems to call it. Checking the error message, it seems to be completely ignoring this code because it shows the URI inside of a  `NetworkImage` even if I've specified a different widget, like the `SvgPicture`

**Comment by KagurazakaHanabi** [comment]
Sorry for my mistake...

https://github.com/flutter/flutter_markdown/blob/880689500d6b0d13cd582e410870b53b3972cc29/lib/src/widget.dart#L139

**Comment by ThinkDigitalSoftware** [comment]
Thank you for fixing this. I think you'll need to open a new PR since your other one was merged

**Comment by ThinkDigitalSoftware** [comment]
@KagurazakaHanabi @domesticmouse has the new fix been merged? The version number didn't see to change.

**Comment by ThinkDigitalSoftware** [comment]
Any idea on what the fix is for this? I'll submit it, It's just setting me back at the moment

**Comment by ThinkDigitalSoftware** [comment]
Just found out this was fixed...

**Comment by mayurdhurpate** [comment]
This issue was fixed in which version? I faced this issue in  v0.3.0.

**Comment by ThinkDigitalSoftware** [comment]
Try running packages upgrade. It's on 0.3.0

**Comment by ThinkDigitalSoftware** [comment]
@mayurdhurpate 
Try running packages upgrade. It's on 0.3.0. Here's the line of code that needed to be in there.
https://github.com/flutter/flutter_markdown/blob/b7f66ec3136a3d4cac6a241d21f60264c22dbc81/lib/src/widget.dart#L139-L146
