### ISSUE TITLE
Add ability to render certain tags ourselves

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter_markdown#144]
I would like to be passed a Markdown "element" if I choose for rendering myself. Sometimes the stylesheet isn't enough. For example, I want to use a Flutter Widget that includes syntax highlighting for dart. I tried using their syntax highlighter class with this library, but it was riddled with errors. If we have a parameter for that, it would add a lot of flexibility. Or if the code for rendering each element was broken out into individual overridable functions for those extending the class, we could effectively accomplish the same thing

**Comment by KagurazakaHanabi** [comment]
I found [a syntax highlight library](https://github.com/pd4d10/highlight) maybe can help you to build your `SyntaxHighlighter` class

**Comment by ThinkDigitalSoftware** [comment]
That's the one I wanted to use I believe, but I wasn't using it right. I ended up getting it working now. I still like the idea of rendering certain widgets ourselves and we can get passed the data from the renderer. I'm not sure how difficult that would be to implement
