### ISSUE TITLE
Add support for SelectableText

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter_markdown#146]
This way, if we want to user to be able to copy rendered text, we can use a boolean in the markdown widget

**Comment by ThinkDigitalSoftware** [comment]
@KagurazakaHanabi  did you make a commit for this or something? I feel like I saw one, so I closed it

**Comment by KagurazakaHanabi** [comment]
Set `Markdown.selectable` to `true`

**Comment by ThinkDigitalSoftware** [comment]
Beautiful, thanks

**Comment by ThinkDigitalSoftware** [comment]
@KagurazakaHanabi on checking, i only get the option to select all, not a standard selector when holding on text on iOS at least. I haven't yet tested on Android

**Comment by ThinkDigitalSoftware** [comment]
Nevermind. You just have to do it just right..

**Comment by norbertkross** [comment]
@KagurazakaHanabi  Where to add  `Markdown.selectable to true`

**Comment by briceAlex** [comment]
Hi,
how I can copy the style ( bold etc..) too ?
