### ISSUE TITLE
Counted lists are gonna centered (?!)

### ISSUE THREAD

**Issue by Ahmadre** [flutter/flutter_markdown#150]
My counted lists are gonna centered vertically (the numbers). Why? I want it like real markdown on the first line! 😢 

<img width="803" alt="Bildschirmfoto 2019-11-22 um 23 56 23" src="https://user-images.githubusercontent.com/18512224/69466246-cc702580-0d83-11ea-834c-1aa6f0215606.png">

**Comment by Ahmadre** [comment]
Same problem for bulleting lists :(

**Comment by KagurazakaHanabi** [comment]
It’s fixed but the pr is not merged #143
