### ISSUE TITLE
imageBuilder is getting ignored

### ISSUE THREAD

**Issue by SunlightBro** [flutter/flutter_markdown#160]
The `MarkdownWidget` ignores the
- `widget.imageBuilder`
- `widget.checkboxBuilder`

This is getting fixed in version **0.3.2** but this version does not run on `flutter channel stable`.
The latest version I was able to run on `stable` was **0.3.0**, where this issue still exists.

For a production app I don't want to move to flutter channel `beta` or `dev`, to be able to use this package.

**Comment by domesticmouse** [comment]
Thanks @SunlightBro
