### ISSUE TITLE
Dashes with space between them ('- -') break the widget

### ISSUE THREAD

**Issue by Pavel-Sulimau** [flutter/flutter_markdown#165]
**When I use  '- -' or 'hello\n- -' (notice the space) as `Markdown` `data` the widget throws an exception:**

> Exception has occurred.
> RangeError (RangeError (index): Invalid value: Valid value range is empty: 0)

![image](https://user-images.githubusercontent.com/8143332/70459184-b1601e00-1ac4-11ea-94f2-d1c6466b1549.png)
![image](https://user-images.githubusercontent.com/8143332/70459669-ba052400-1ac5-11ea-9a97-9d0c618c8729.png)
But if there is no space everything works as expected:
![image](https://user-images.githubusercontent.com/8143332/70459796-fdf82900-1ac5-11ea-8e5a-4175cd3815fd.png)

**Steps to Reproduce:**
1. Create an app using this piece of code:

``` dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Markdown Error'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(8.0),
          child: MarkdownBody(data: 'hello\n- -'),
        ),
      ),
    );
  }
}
```
2. Run the app and observe the result.

**Environment info**

flutter_markdown: **0.3.0**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-BY)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by KagurazakaHanabi** [comment]
It's fixed in 0.3.1, see https://github.com/flutter/flutter_markdown/issues/145#issuecomment-553741205
BTW, https://github.github.com/gfm/#setext-heading
> The setext heading underline cannot contain internal spaces

**Comment by Pavel-Sulimau** [comment]
Thanks for your response, I tried v0.3.2 yesterday and saw that the issue is fixed there, but I'm just not fond of depending on non-stable versions of libs/sdks in production apps, and v3.0.1+ doesn't work with latest stable (v1.9.1+hotfix.6 as of now) Flutter SDK.
BTW, I saw that specification and know the rules, but, obviously, I cannot ensure that every user of my app reads specifications from cover to cover and types in only the expected combinations of symbols :)

**Comment by domesticmouse** [comment]
Hi @Pavel-Sulimau, I'd suggest you investigate the current beta release in preparation for the next stable release.
