### ISSUE TITLE
Figure out how to use Cirrus and/or Travis to test both Stable and Beta on submit

### ISSUE THREAD

**Issue by domesticmouse** [flutter/flutter_markdown#179]
This is a backlog ticket for the issue raised by @mit-mit in https://github.com/flutter/flutter_markdown/pull/166

**Comment by domesticmouse** [comment]
Hey @kevmoo can I get some help with this?

**Comment by kevmoo** [comment]
See https://github.com/dart-lang/shelf/blob/master/.travis.yml

**Comment by kevmoo** [comment]
Oh...custom script. You'll have to use a matrix for that, I think.
