### ISSUE TITLE
markdown toc supported

### ISSUE THREAD

**Issue by asjqkkkk** [flutter/flutter_markdown#188]
Hi, Can this library support the TOC function of markdown？

Just like this：
```
MarkdownBody(
...
  toc:(List<String> titles, int index){
  
  }
...
);
```

**Comment by maks** [comment]
As far as I'm aware neither the original [Markdown spec](https://daringfireball.net/projects/markdown/syntax) nor [Commonmark](https://spec.commonmark.org/0.29/) specify table of contents functionality?

**Comment by asjqkkkk** [comment]
> As far as I'm aware neither the original [Markdown spec](https://daringfireball.net/projects/markdown/syntax) nor [Commonmark](https://spec.commonmark.org/0.29/) specify table of contents functionality?

I am buildingmy personal blog through flutter web. So it's an important function for me.

**Comment by maks** [comment]
> I am buildingmy personal blog through flutter web. So it's an important function for me.
> 
> 
> 

@asjqkkkk That's understandable, but it's very difficult for anyone else to know exactly what functionality you are requesting or how it should be implemented as there is nothing in the markdown or commonmark specs that document it.

**Comment by asjqkkkk** [comment]
> > I am buildingmy personal blog through flutter web. So it's an important function for me.
> 
> @asjqkkkk That's understandable, but it's very difficult for anyone else to know exactly what functionality you are requesting or how it should be implemented as there is nothing in the markdown or commonmark specs that document it.

😂Thank you
During the time I first filed an issue and waited for a reply, I implemented this feature myself
https://pub.dev/packages/markdown_widget
