### ISSUE TITLE
Doesn't support checkbox yet

### ISSUE THREAD

**Issue by XinwenCheng** [flutter/flutter_markdown#190]
Current version <code>0.3.3</code> doesn't support checkbox yet, that means it doesn't render [x] and [ ] in markdown content.

Please improve, thanks in advance!

**Comment by XinwenCheng** [comment]
Sorry, my fault. After checked example, checkbox must be written as <code>- [x]</code> or <code>- [ ]</code>, and it works good.

**Comment by domesticmouse** [comment]
I'm unsure if Github's markdown parser accepts a different syntax for checkboxes, and if it does feel free to raise issues against https://pub.dev/packages/markdown =)
