### ISSUE TITLE
Dark Theme doesn't support code blocks and tables

### ISSUE THREAD

**Issue by mrpvb-pvbk** [flutter/flutter_markdown#203]
### Code Blocks:
**_By default without SyntaxHighlighting_**
![S00321-210932](https://user-images.githubusercontent.com/44783405/77233428-645a1080-6bb8-11ea-9ae0-56f41a1c52bd.jpg)

### Tables
![S00321-210838](https://user-images.githubusercontent.com/44783405/77233448-7a67d100-6bb8-11ea-9e21-22850437e4b4.jpg)

**Comment by bierbaumtim** [comment]
I am currently working on the dark theme from CupertinoTheme, which has some similar problems. Therefore I will also check dark theme from MaterialTheme.
