### ISSUE TITLE
markdown view not working inside listview item

### ISSUE THREAD

**Issue by softmarshmallow** [flutter/flutter_markdown#207]
```
Assertion failed: file:///Users/softmarshmallow/development/flutter/packages/flutter/lib/src/rendering/box.dart:1694:12
hasSize
"RenderBox was not laid out: RenderRepaintBoundary#7883d relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE"
The relevant error-causing widget was: 
  ListView file:///Users/~~~/lib/screen/search_screen.dart:46:24
```

which i know it seems simple size related problem, but it worked fine even with columns inside listview's item

**Comment by softmarshmallow** [comment]
my bad. adding shirinkWrap: true did the job

**Comment by SalathielGenese** [comment]
Good catch @softmarshmallow . It now displays but doesn't scroll.

**Comment by softmarshmallow** [comment]
mine does scroll but bit glitchy. but my project is fine, due its purposed on desktop usage. @SalathielGenese  why dont you look at custom scroll physics? it might help

**Comment by brooth** [comment]
In addition to `shrinkWrap: true` use `physics: ClampingScrollPhysics()`

**Comment by yumi0629** [comment]
1. Use ```MarkdownBody``` instead of ```Markdown```
2. Set ListView with attributes ```shrinkWrap: true``` and ```physics: ClampingScrollPhysics()```

**Comment by softmarshmallow** [comment]
Want me to re-open this for most acceptable workaround?
