### ISSUE TITLE
The param "height" of `p` elements performs strange

### ISSUE THREAD

**Issue by yumi0629** [flutter/flutter_markdown#208]
I set my own style sheet to my Markdown widget, and give the `p` elements with height 4:
```
const String _markdownData = """
## Titles

Setext-style
Setext-style
Setext-style
Setext-style
Setext-style

""";

Markdown(
      styleSheet: MarkdownStyleSheet(
 p: TextStyle(
          fontSize: 16,
          color: Colors.black87,
          height: 4,
        ),
shrinkWrap: true,
selectable: true,
data: _markdownData,
)
```
What I want is below:
![image](https://user-images.githubusercontent.com/17703630/78622257-4a5a4680-78b7-11ea-99b2-a9e5f54dba66.png)
But what I get is:
![image](https://user-images.githubusercontent.com/17703630/78622321-6a8a0580-78b7-11ea-8a05-9e1d4f3a9f43.png)
I use it in Flutter Web application, run with device Chrome.

**Comment by mjordan56** [comment]
Hi @yumi0629. I think what you're looking for is the `blockSpacing` parameter to the MarkdownStyleSheet class. The flutter_markdown package lays out the Markdown block elements in a column. Between each Markdown block element, it inserts a SizedBox widget. The default height of this SizeBox widget is 8.0. You can control the height of the SizeBox widget by specifying a `blockSpacing` value. Here's what that would look like in your code example:

```
Markdown(
  styleSheet: MarkdownStyleSheet(
    p: TextStyle(
      fontSize: 16,
      color: Colors.black87,
      height: 4,
    ),
    blockSpacing: 36.0, // <== Or whatever spacing value you want
    shrinkWrap: true,
    selectable: true,
    data: _markdownData,
)
```
Be aware that this value is applied to *all* the SizeBox widgets separating your Markdown block elements. In your example, this appears to be exactly what you are looking for.

**Comment by domesticmouse** [comment]
Closing out. If you believe this is still an issue, please comment and I will re-open.
