### ISSUE TITLE
Headings in cupertino StyleSheet are white

### ISSUE THREAD

**Issue by TheKashe** [flutter/flutter_markdown#211]
Headings in cupertino style sheet (either by passing enum or creating stylesheet from theme data) are white.

The only workaround I found is:
`MarkdownStyleSheet.fromCupertinoTheme(CupertinoThemeData()).merge(
                    MarkdownStyleSheet(
                        h1:TextStyle(color:Colors.black,
                        fontWeight: FontWeight.w500,
                        fontSize: CupertinoThemeData().textTheme.textStyle.fontSize + 10,
                        )))`

Which is copying hardcoded style from MarkdownStyleSheet, which is bad.

Am I missing something obvious?

**Comment by bierbaumtim** [comment]
No you are right. That's will be fixed with #210 .

**Comment by mjordan56** [comment]
@domesticmouse This issue was fixed by PR #210.
