### ISSUE TITLE
[Feature Request] Get plain text of markdown content

### ISSUE THREAD

**Issue by XinwenCheng** [flutter/flutter_markdown#220]
Hi devs,

Is there possible way to get plain text of markdown content? For instance, I hope to get `Hello, world!` from markdown *Hello, world!*, etc.

This is for TTS, otherwise it will speak out asterisk as a word.

Hope you guys could help, thanks in advance!

**Comment by domesticmouse** [comment]
Have you looked at the [`markdown`](https://pub.dev/packages/markdown) package?

**Comment by mjordan56** [comment]
Hi @XinwenCheng, the description of the problem you're trying to solve is fairly terse and is open to multiple interpretations. I'm going to take your question at face value and try not to insert anything more than what I believe is your question.

That said, I agree with @domesticmouse, you should look at the Dart markdown package and not the flutter_markdown package. If all you want is the text from Markdown source data you should look at using the markdown package to parse the data and create an abstract syntax tree (AST). Once you have the AST you can traverse the nodes of the AST with your own class that implements the NodeVisitor interface. The AST created by the markdown package will consist of Element and Text nodes. The Element nodes have the formatting and structure metadata information. The Text nodes have just the text content from the Markdown source data. Note that you will need to give context and join the text from the Text nodes appropriately. For example, a sentence with an emphasis string in the middle will generate three Text nodes, one for the pre-emphasis text, one for the emphasis text, and one for the post-emphasis text. This text will just be the raw text, no Markdown syntax tags.

If you want to see an example of a class that implements the NodeVisitor interface, you can look at the MarkdownBuilder class in the builder.dart file of the flutter_markdown package. Look at the visitElementBefore, visitText, and visitElementAfter methods.

**Comment by domesticmouse** [comment]
Closing this out for now. Thanks all
