### ISSUE TITLE
Adding break line (white line) doesn't work

### ISSUE THREAD

**Issue by lzhuor** [flutter/flutter_markdown#221]
I tried to add breakline (white line) in `markdownData` with 
```
#Header
\ // next line with backslash

Next paragraph

// nextline with enter
```

None of them works.

flutter_markdown: ^0.3.5
Flutter v1.1.7 stable

**Comment by AndroidNils** [comment]
`Line1\Line2  Line1<br>Line2  Line1<br/>Line2  Line1\nLine2`
Also doesn't work...

**Comment by lzhuor** [comment]
@domesticmouse Thanks for maintaining this library. Sorry to tag you. Could you please help take a look? This is more urgent I guess.

**Comment by domesticmouse** [comment]
Can you see if this replicates with just https://pub.dev/packages/markdown? I want to understand if this is a bug in the markdown parser, or if it is the postprocessing that flutter_markdown does after markdown has parsed the content.

**Comment by lzhuor** [comment]
Hi @domesticmouse , thanks! Yes, I did. It works fine in https://pub.dev/packages/markdown

Please see snapshot attached for your reference. 
![image](https://user-images.githubusercontent.com/14172220/82867594-bc691680-9f5d-11ea-826d-60c1f8757cad.png)

**Comment by lzhuor** [comment]
Hi @domesticmouse, as I found above, it should be an issue in this library. 

Could you please point me to somewhere? so I can take a look and PR. 

Thank you very much

**Comment by domesticmouse** [comment]
Hi @lzhuor, I'm curious what you would like me to point you to? The github repo is https://github.com/flutter/flutter_markdown/

hth, brett

**Comment by lzhuor** [comment]
@domesticmouse I was curious if you could give me a hint or direction about which function or file could be causing the issue.

**Comment by domesticmouse** [comment]
@lzhuor if I knew that, I’d fix it myself. Time to break out the debugger, methinks.

**Comment by lzhuor** [comment]
@lzhuor If you are more friendly, I'd debug it and PR. Time to close this issue and fork it, methinks.

**Comment by domesticmouse** [comment]
@lzhuor Just to comment on your deleted response, I don't know this code, so I can't give you guidance on where precisely to get started with this fix. While you are well within your rights to fork the project and fix it on your own fork only, you do a disservice to both yourself and the community at large by doing so.

Flutter is effectively a startup, we have ambitions a lot larger than our reach. We are attempting to make all of UI development better, on all sorts of screens. We don't have enough engineers on the team to do it alone, and we can only succeed with our community.

I'm sorry you found my message less than welcoming, but the truth of the matter is that I don't have the bandwidth to handhold you through figuring out how to add this feature. If and when I find the time to figure out how to add this feature, I will also do the fix, as figuring out where to do the change is a large portion of the work.

**Comment by lzhuor** [comment]
> @lzhuor Just to comment on your deleted response, I don't know this code, so I can't give you guidance on where precisely to get started with this fix. While you are well within your rights to fork the project and fix it on your own fork only, you do a disservice to both yourself and the community at large by doing so.
> 
> Flutter is effectively a startup, we have ambitions a lot larger than our reach. We are attempting to make all of UI development better, on all sorts of screens. We don't have enough engineers on the team to do it alone, and we can only succeed with our community.
> 
> I'm sorry you found my message less than welcoming, but the truth of the matter is that I don't have the bandwidth to handhold you through figuring out how to add this feature. If and when I find the time to figure out how to add this feature, I will also do the fix, as figuring out where to do the change is a large portion of the work.

Thanks @domesticmouse for explaining it. 

Firstly, I apologize for my deleted comments. It wasn't written in a thoughtful way and it didn't help anyone in the community. 

Secondly, I absolutely understand that this is an open-sourced project and this is not my first opening issues in Dart/Flutter. I'd glad to help to fix it and contribute my tiny effort to get the community better as what I and many others have done.

Lastly, I did find the previous message less than welcoming. However, thanks for explaining it. Will PR soon.

**Comment by domesticmouse** [comment]
Thank you for your understanding @lzhuor. I’ll work towards being more welcoming in the future. 

I look forward to reviewing your PRs 😁

**Comment by lzhuor** [comment]
so I found the issue is in `_parseMarkdown`:
- `flutter_markdown` are parsing markdown data `String` to `List<String>` by `RegExp(r'\r?\n')`.
- `dart/markdown` only create `br` tag to empty line when a string matches `  \n` ([space, space, \n]) . 

`flutter_markdown` never feeds `  \n` even users type so because `\n` is split.
