### ISSUE TITLE
Perfomance problems

### ISSUE THREAD

**Issue by braindamagedman** [flutter/flutter_markdown#224]
MarkdownBody causes to FPS drop when parse pretty small markdown document.

You can find sample app here: https://github.com/braindamagedman/flutter_issues_sample

When Page2 opens about 10 frames dropped.

Screen from DevTools:
![Screenshot from 2020-05-19 23-56-15](https://user-images.githubusercontent.com/1287597/82335776-226d0f80-9a2d-11ea-9a45-417ae511c97d.png)

Flutter doctor:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Community Edition (version 2018.3)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by braindamagedman** [comment]
I uploaded timeline json exported from DevTools: https://github.com/braindamagedman/flutter_issues_sample/blob/master/timeline_2020_5_19-1589896543326000.json

You can import it folowing this instruction: https://flutter.dev/docs/development/tools/devtools/timeline#import-and-export

**Comment by domesticmouse** [comment]
I suspect what we need to do here is to push parsing the markdown content to a background thread and/or give users the option to parse markdown content at compile time for static content.

Hmm.

**Comment by braindamagedman** [comment]
> I suspect what we need to do here is to push parsing the markdown content to a background thread and/or give users the option to parse markdown content at compile time for static content.
> 
> Hmm.

I put static marcdown data for testing purpose. In my real app  data downloaded from server. It would be grate to have any solution to do heavy work in background and pass result to UI.

**Comment by RobertBrunhage** [comment]
Any updates on this? This could be huge as I usually use this to display markdown in Dialogs but they lag if I set it directly. 

As of now I have to wait until the dialog animation is finished and then set it.

**Comment by domesticmouse** [comment]
The status update for this PR is that I am awaiting someone inventing 48 hour days, and failing that, we accept pull requests. =)

**Comment by domesticmouse** [comment]
I have had a quick dig into this issue, and to change out the parsing strategy would be a large refactor, and as a bonus, I have no real idea on how to handle the lack of isolates on web. I'd suggest for your usecase to investigate inflating the Flutter Markdown widget tree in an isolate, and patch it into the tree via a `FutureBuilder`.
