### ISSUE TITLE
Feature: expose MarkdownBuilder for custom Image 

### ISSUE THREAD

**Issue by pedia** [flutter/flutter_markdown#23]
I need to add onTap to Image into Markdown.

Currently, it's impossible.

```
class MarkdownBuilder implements md.NodeVisitor {
   Widget _buildImage(String src) {
```

How about this feature?

**Comment by xqwzts** [comment]
Thanks for reporting this, added support for nesting images in links and having them react to clicks, so you can now do:

```
[![alt](imgUrl)](link)
```

And the `onTap` handler will be called.

**Comment by pedia** [comment]
@xqwzts 
Thanks for ur reply.

@DaveShuckerow
I think the solution is not the best since we must modify the content.
Flutter does not support HTML markdown is more important.

I even changed my web server, render as markdown instead of HTML.

**Comment by pedia** [comment]
I create a pr #26
