### ISSUE TITLE
Add a possibility to change list padding

### ISSUE THREAD

**Issue by furaiev** [flutter/flutter_markdown#238]
Hi, thank you for your package,

Could you please make the padding in the list adjustable? Currently, it's hardcoded as 4:
https://github.com/flutter/flutter_markdown/blob/a77211e67bae532257d0338ba11c7858546f0f45/lib/src/builder.dart#L407

**Comment by cebr76** [comment]
Hey, we would like to work on this as our first issue :) are you okay with that?

**Comment by mjordan56** [comment]
@furaiev PR #306 addresses this feature request.

@domesticmouse This feature request has been implemented in PR #306.
