### ISSUE TITLE
A Better Flutter Markdown Example App

### ISSUE THREAD

**Issue by mjordan56** [flutter/flutter_markdown#246]
The current example app bundled with the Flutter Markdown package is minimally useful at best. IMHO, the example Markdown source data, doesn't show the package's capabilities very well and is even misleading in some of the formatted content. Here are some of the problems I see with the example:

- The Titles section shows the Markdown Setext and Atx styles as code and not as the resulting formatted text headers.
- The task list items imply they can be selected when they are not selectable.
- The "Google's Homepage" link isn't connected to anything, so it looks like the link doesn't work.
- The "Center Title" has a comment "* How to implement it see main.dart#L129 in example." Yet, there is no explicit information contained in the main.dart file on implementing centering titles. I assume the problem is that while the MarkdownElementBuilder class defined for the center header, there isn't an accompanying block syntax. (Also, why is this included? It seems to me that the wrap alignment property already addresses centering elements.)
- The subscript example doesn't display formatted subscript output. The reason there is no formatted subscript output is that the SubscriptSyntax class is defined, but an instance of the class is not provided to the Markdown parser to include in the inline parsing process.

I want to propose that a better, more useful example be created that demonstrates to users how to use the features of the flutter_markdown package. The example needs to display the formatted RichText output from a Markdown or MarkdownBody widget, display the raw Markdown source data, and any notes or comments to help the user understand the example. Since there are many permutations when configuring the Markdown widget and the underlying Markdown parser, the example should allow multiple discrete mini-examples within the example. Adding new mini-examples should be a straight-forward and simple process.

I want to propose the following solution, a simple example app that shows a list of mini-examples. Selecting a mini-example from the home page brings in a demo page with three tabs; Formatted displaying the formatted output, Raw displaying the raw Markdown source data, and Notes for displaying notes and comments about the example to clarify or explain the mini-example. To add new mini-examples to the example app a new widget is created that implements MarkdownDemoWidget and an instance of the mini-example widget is added to the home page demo widgets list.

I have a prototype of an example app that meets these criteria.

![2020-07-24 15 25 55](https://user-images.githubusercontent.com/6308118/88436807-56183d00-cdc2-11ea-8c3d-49526b216caa.gif)

I'm looking for feedback and comments from the flutter_markdown community on this proposal. Please leave your feedback and comments. Thank you!

**Comment by domesticmouse** [comment]
If no one else objects I'm happy for @mjordan56 to move ahead with replacing the sample with this improved sample.

Thoughts?

**Comment by vizel** [comment]
Hello @mjordan56 ,
thank you for contributing a better example app. I'm new in flutter and would appreciate it to get a look in your example-code for own usage. Would you send it to me?

**Comment by mjordan56** [comment]
Hi @vizel , welcome to the world of Flutter. I always enjoy hearing about people joining the ranks of Flutter developers. @domesticmouse has given me the go-ahead to replace the existing flutter_markdown example with the changes I've proposed. I'm in the process of making my final changes and clean-up of the code in preparation for submitting a pull request with the changes. You will be able to get my example code from the GitHub repository here soon.

**Comment by mjordan56** [comment]
@vizel, my proposed changes for a better example app have now been submitted, reviewed, and approved. You can get the code in the [example](https://github.com/flutter/flutter_markdown/tree/master/example) directory for the flutter_markdown package.

**Comment by domesticmouse** [comment]
Closing out
