### ISSUE TITLE
MarkdownWidget and Its Descendants Need to Expose blockSyntaxes and inlineSyntaxes

### ISSUE THREAD

**Issue by mjordan56** [flutter/flutter_markdown#259]
The proper method for including custom block and inline syntaxes to the markdown package Document is through the blockSyntaxes and inlineSyntaxes parameters and not by modifying the pre-define extension set properties. The MarkdownWidget and its children, Markdown and MarkdownBody, need to add blockSyntax and inlineSyntax parameters that can be used by consumers of the flutter_markdown package to add custom syntax parsers. MarkdownWidget can then pass these lists on to the Document to be used in the parsing of the Markdown content.

**Comment by domesticmouse** [comment]
Closing out as #269 fixes this issue.
