### ISSUE TITLE
Builders for existing tags aren't working

### ISSUE THREAD

**Issue by moi42** [flutter/flutter_markdown#262]
I was working on adding builders for headers and the methods `visitText()` and `visitElementAfter()` weren't invoked. So i run the [example](https://github.com/flutter/flutter_markdown/blob/master/example/lib/demos/centered_header_demo.dart) provided and the implementation showed for builders isn't working, the centered title isn't centered. 

![Screenshot_1598237979](https://user-images.githubusercontent.com/23005670/90999360-00cf7700-e58c-11ea-894c-ebc4646dda48.png)

**Comment by brightknight08** [comment]
I encountered this too.  I was rather trying to add some padding to the top of h2 tags.

for aligning the tags (if that is what you are after), you may try:
```dart
     child: Markdown(
         data: legalDoc,
         styleSheet: MarkdownStyleSheet.fromTheme(Theme.of(context)).copyWith(
             h1Align: WrapAlignment.center,
          ),
```
