### ISSUE TITLE
doesn't work with multi line strings

### ISSUE THREAD

**Issue by sgehrman** [flutter/flutter_markdown#263]
if you use a multline string with three single quotes, it doesn't work

```
class ResumeScreen extends StatefulWidget {
  @override
  _ResumeScreenState createState() => _ResumeScreenState();
}

class _ResumeScreenState extends State<ResumeScreen> {
  String _contactString() {

   // this doesnt work!!   <==================
    return '''
     [steve@xx.com](mailto:steve@xx.com)
     ''';
  }

  String _experienceString() {
    return '[steve@xx.com](mailto:steve@xx.com)';
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Resume')),
      body: SingleChildScrollView(
        physics: const BouncingScrollPhysics(),
        child: Column(
          children: [
            MarkdownText(_contactString()),
            MarkdownText(_experienceString()),
          ],
        ),
      ),
    );
  }
}

class MarkdownText extends StatelessWidget {
  const MarkdownText(
    this.text, {
    this.fontSize,
  });

  final String text;
  final double fontSize;

  @override
  Widget build(BuildContext context) {
    return MarkdownBody(
      styleSheet: MarkdownStyleSheet(
        p: TextStyle(
          height: 1.4,
          fontSize: fontSize,
        ),
      ),
      onTapLink: (url) {
        Utils.launchUrl(url);
      },
      data: text,
    );
  }
}

```

**Comment by sgehrman** [comment]
It works if I use trim() on the multi line string, I guess it doesn't like the whitespace on front of string?

**Comment by lzhuor** [comment]
@sgehrman Yes, the whitespace at the front of a string could cause this issue. It's also related to how this library parse the node to HTML tags. 

Related to: #261 

We might need to find a better way of handling the trailing white spaces (multiple lines).

**Comment by mjordan56** [comment]
Hi @sgehrman. The issue you are seeing is not related to #261. The behavior you are seeing is correct Markdown syntax behavior according to the [CommonMark](https://spec.commonmark.org/0.29/) and [GitHub Flavored Markdown](https://github.github.com/gfm/) specifications. Basically, any line of text in a Markdown document that begins with 4 or more spaces is considered to be an [indented code block](https://github.github.com/gfm/#indented-code-block). The way you are creating your Markdown source data in your code example, using a multi-line string literal, is including the leading spaces from your source code indenting format which in your case is greater than 3 space characters.

You can verify this behavior in both the [Markdown Live Preview](markdownlivepreview.com) and [Dart Markdown Live Editor](dart-lang.github.io/markdown/). Enter your test string `[steve@xx.com](mailto:steve@xx.com)` into either online editor. When there are 3 or fewer leading spaces the text is interpreted as a link. Once there are 4 or more leading spaces the text is interpreted as an indented code block.

If you're going to define your Markdown source data in a multi-line string I'd recommend defining it outside of your class like this:

```
const String _contactString = '''
[steve@xx.com](mailto:steve@xx.com)
''';

class ResumeScreen extends StatefulWidget {
  @override
  _ResumeScreenState createState() => _ResumeScreenState();
}

class _ResumeScreenState extends State<ResumeScreen> {
...
}
```
This will ensure you are explicitly setting the leading spaces as you want them to be.

**Comment by domesticmouse** [comment]
Closing out. If you believe this is still an issue, please comment and I will re-open.
