### ISSUE TITLE
Organize Tests Into Discrete Units

### ISSUE THREAD

**Issue by mjordan56** [flutter/flutter_markdown#270]
The flutter_markdown test file, flutter_markdown_test.dart, is becoming large and difficult to navigate. Finding specific tests can be challenging to easily find. I'd like to propose separating the tests into logical groups in individual files. For example, basic block Markdown elements in basic_block_elements.dart, complex elements like lists and tables in markdown_list.dart and markdown_table.dart, etc. This will increase the cohesion of the tests.

**Comment by domesticmouse** [comment]
I’m guessing the merge of https://github.com/flutter/flutter_markdown/pull/272 is sufficient to close this issue?

**Comment by mjordan56** [comment]
Yes, PR #272 closes this issue. In my mind I try to make both my issues
reported and the fix PRs as atomic as possible. If there are additional
issues they should be opened and resolved in other discrete and focused
fixes.

Michael

**Comment by domesticmouse** [comment]
Thanks @mjordan56, closing...
