### ISSUE TITLE
Chinese display problem

### ISSUE THREAD

**Issue by Lifufa** [flutter/flutter_markdown#271]
Chinese display is incomplete

**Comment by mjordan56** [comment]
@Lifufa Your issue description is very terse. Can you be more specific about what exactly is incomplete about Chinese display? Dart strings are a sequence of UTF-16 code units. This should be sufficient for displaying both simplified and traditional Chinese glyphs. Can you provide an example of the Markdown source that isn't be displayed correctly? Have you tried using the [Dart Markdown Live Editor](https://dart-lang.github.io/markdown/) to see how it displays Chinese?

More information is necessary to be able to coherently respond to your issue.

**Comment by mjordan56** [comment]
@domesticmouse Brett, I think this issue should be closed. @Lifufa hasn't provided any additional information to help identify whether or no a bug or other problem is present. I also take the emoji thumbs down for Lifufa's comment and the thumbs up for my comment as support and agreement from other users.

**Comment by domesticmouse** [comment]
Thanks @mjordan56
