### ISSUE TITLE
Leading Spaces At Beginning Of Next Line Aren't Ignored

### ISSUE THREAD

**Issue by mjordan56** [flutter/flutter_markdown#279]
The leading spaces at the beginning of the next line of text in a paragraph aren't ignored after a soft line break.

Both the [CommonMark](https://spec.commonmark.org/0.29/#example-646) and [GitHub Flavored Markdown](https://github.github.com/gfm/#example-670) specifications note in the section on **Soft line breaks** that "_A regular line break (not in a code span or HTML tag) that is not preceded by two or more spaces or a backslash is parsed as a softbreak. Spaces at the end of the line and beginning of the next line are removed_"  (click on the document links to go to the examples in the specifications). The example from both specs show the example Markdown input data:

```
foo・
・bar
 ```
should produce the following output:
```
foo・bar
```
However, the flutter_markdown package does not properly trim remove the extra spaces and produces the following incorrect output:
```
foo・・bar
```
This is also true of cases with more leading spaces on the second line. For example:
```
foo・
・・・・・・bar
 ```
Produces the following output:
```
foo・・・・・・・bar
```

**Comment by domesticmouse** [comment]
Is this fixed by https://github.com/flutter/flutter_markdown/pull/280?
