### ISSUE TITLE
Relative remote images do not render

### ISSUE THREAD

**Issue by SebastiaandenBoer** [flutter/flutter_markdown#28]
Currently, the following happens:

- Either the URL is absolute and the image is retrieved over the network.
- The URL is deemed invalid/ an imageDirectory is set, but the image is always loaded as if it was locally.

An Dart IO Directory can also point to the network. Therefore, wouldn't it be better to test if the imageDirectory + path equals to a network path before retrieving the image?

**Comment by DaveShuckerow** [comment]
For clarification, what do you mean by a relative remote path?  What is the remote path relative to?

An example to illustrate the case you have in mind would be most helpful.

**Comment by SebastiaandenBoer** [comment]
For instance, I'm currently encountering a web service where all links to image are passed on as relative paths to the root of the site (e.g. ```/media/images/donald_duck.png```.

As a Dart IO Directory can also point to a network host/ path, it is possible to use the host of the web service as the Dart IO Directory, resulting in something like ```https://www.webservice.com/media/images/donald_duck.png```.

However, in the markdown library the current implementation presumes that the path is a local file directory whenever a directory is set. As it also possible this could be a host, I propose to perform another check to see if the directory is a valid URL instead of assuming it is a local directory. That way, images with relative remote paths can be retrieved from a remote network with a host set as the directory.

**Comment by westy92** [comment]
It looks like we might be able to pass through the `imageLinkResolver` from the [underlying library](https://github.com/dart-lang/markdown/blob/master/lib/src/document.dart#L15).
