### ISSUE TITLE
Example App Gives "Older Version of the Android Embedding" Warning

### ISSUE THREAD

**Issue by mjordan56** [flutter/flutter_markdown#283]
The flutter_markdown example app was created with pre-1.12 Android project embedding. This causes the following warning message to be displayed in the debug console when running the example app:

```
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at
https://flutter.dev/go/android-project-migration
to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
The example app needs to upgrade the old deprecated Android platform-side wrappers hosting the Flutter runtime at `io.flutter.app.FlutterActivity` and their associated classes to the new wrappers at `io.flutter.embedding.android.FlutterActivity` and the associated classes that now replace them.

**Comment by domesticmouse** [comment]
Fixed by #284
