### ISSUE TITLE
Feature Request: Include the link text in the onTapLink callback

### ISSUE THREAD

**Issue by dooven** [flutter/flutter_markdown#286]
Hi Flutter team. Thanks for this great library! I do have a feature request for y'all :heart: 

Currently the [MarkdownTapLinkCallback](https://pub.dev/documentation/flutter_markdown/latest/flutter_markdown/MarkdownTapLinkCallback.html) only include href in the callback. It'd be nice if the link text is also added in the callback. 

My use case for this is I use flutter_markdown to render a text that contains a username as the label + user profile link as the href & I want to get a hold of the label after i tap the link.

**Comment by domesticmouse** [comment]
This is implemented in #288
