### ISSUE TITLE
Add support for tables

### ISSUE THREAD

**Issue by dotdoom** [flutter/flutter_markdown#29]
As https://github.com/flutter/flutter/issues/8240 asks, please add support for Markdown tables.

**Comment by xqwzts** [comment]
It looks like @ilikerobots already did most of the work required for that, it's been more than a year so I suppose it's safe to assume they've moved on from it - I'll take a look at porting their work over.

**Comment by ilikerobots** [comment]
yep, moved on temporarily, but making my way back.  If you got a handle on it, @xqwzts, then it's probably faster for you to take it since i've been out of the loop for a year.  :bowing_man:

**Comment by CarGuo** [comment]
any support for it now?

**Comment by CarGuo** [comment]
I see that the dependency has been updated to 2.0.2，But it still doesn't support table in 0.1.6？

**Comment by DFreds** [comment]
Any updates?

**Comment by JETBI-Mobile** [comment]
we also really need this feature.
Is there any possibility to get a tables?

**Comment by zhengcan** [comment]
any update?
