### ISSUE TITLE
more features

### ISSUE THREAD

**Issue by pedia** [flutter/flutter_markdown#31]
I noticed flutter_markdown is lacking support:
- space between paragraph.
for beauty text since markdown is the best way to implement complex text.
currently only support code(pre tag)

- custom Image(Widget) creating.
cache image, add customized ImageView

Need these features? I can send a PR for these.

**Comment by DaveShuckerow** [comment]
Feel free to send PRs for these features.  

To make this easier to track, please file an issue for each feature you'd like to see separately:

* Space between paragraphs
* Customized image widget

**Comment by pedia** [comment]
@DaveShuckerow 

I am confused about new Column(in MarkdownBuilder.visitElementAfter), since Mardown Widget contained in a ListView and fewer widgets are better?

Code(name in MarkdownStyleSheet) tag name is 'pre'? Why not just pre?

**Comment by DaveShuckerow** [comment]
To answer why a column is used as well as a ListView: https://github.com/flutter/flutter_markdown/issues/32

The tag names are decided by package:markdown, so you can get a more detailed answer there.  

My understanding is that a codeblock is actually a combination of 'pre' and 'code' in that order.  'code' tags an inline code layout, while 'pre' then 'code' tags a block layout of code.

**Comment by pedia** [comment]
Thank your answer. @DaveShuckerow 
Maybe misunderstanding. The ListView contains every item as a Column.

The widget hierarchy:
└Markdown
 └ListView
  ...
        ├AutomaticKeepAlive
        │└KeepAlive
        │ └NotificationListener<KeepAliveNotification>
        │  └RepaintBoundary-[<0>]
        │   └Column <--- This Column is unnecessary？
        │    └Wrap
        │     └RichText

**Comment by DaveShuckerow** [comment]
Ah, the Column defined in the builder file.  That one wraps the children of an individual block group, like a <p> in a group together.  It's for organizing the internal layout of the widgets.
