### ISSUE TITLE
Markdown lists do not support intrinsic sizing

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter_markdown#311]
After a longer investigation in https://github.com/flutter/flutter/issues/71990#issue-760229867, we figured out that `flutter_markdown` does not support intrinsic height measurement due to the following line of code:

https://github.com/flutter/flutter_markdown/blob/bb8f8fbe868a4d83669df16d989b6ba49c845c8e/lib/src/builder.dart#L324

`CrossAxisAlignment.baseline` does simply not allow intrinsic sizing:

> Intrinsics are not available for CrossAxisAlignment.baseline.

If you want to understand why we need intrinsics, please see https://github.com/flutter/flutter/issues/71990#issuecomment-747149574.

---

The `baseline` change was made in https://github.com/flutter/flutter_markdown/pull/170.

@KagurazakaHanabi: I added a [comment for you](https://github.com/flutter/flutter_markdown/pull/170#discussion_r544753585) on that PR.

---

The conclusion that [@goderbauer arrived at](https://github.com/flutter/flutter/issues/71990#issuecomment-747141796) is:

> Long story, short: If you need intrinsics, you cannot use CrossAxisAlignment.baseline. Or if you want CrossAxisAlignment.baseline you can't use intrinsics. Again, that's not really a new limitation. Previously, we were just silently ignoring the baseline alignment in this combination.

So I would propose that we remove the `baseline` alignment (revert #170) **or** make it optional.  
I think that #169 is more of an edge case than our issue, however, just making `baseline` optional for us would be fine.

Ideally of course, there would be a fix that achieves the same behavior w/o baseline :)

**Comment by domesticmouse** [comment]
Hey @KagurazakaHanabi can you weigh in on this bug? Otherwise I feel like I should revert #170. Thanks!

**Comment by dnfield** [comment]
It might work to just have some kind of flag to set how baselining is handled - one that's more correct but incompatible with intrinsics, and one that's incorrect but allows intrinsics.

**Comment by creativecreatorormaybenot** [comment]
* Testing list alignment here. If I were to designs the lists (in Flutter) without adhering to the Markdown spec, I would simply give the bullet a center cross axis alignment.
* However, I assume that start was used previously because the bullet is aligned at the start.

**Comment by creativecreatorormaybenot** [comment]
@domesticmouse I opened a PR 👍  (#313)
