### ISSUE TITLE
i am getting mark down data from api and  using flutter_markdown  and then double quote is not supporting  

### ISSUE THREAD

**Issue by shivdvaio** [flutter/flutter_markdown#316]
![Screenshot 2021-01-11 at 10 58 47 PM](https://user-images.githubusercontent.com/57656560/104216815-921e8780-5460-11eb-83f2-064d2f208ef6.png)

**Comment by mjordan56** [comment]
@shivdvaio This looks like a character encoding issue. Are you sure the text data you're getting from your API is in UTF-8 encoding? If you need to convert your text data check out the [dart:convert library](https://api.dart.dev/stable/2.10.5/dart-convert/dart-convert-library.html). If this isn't a text encoding error, please provide more information about how to reproduce the problem. A sample of the source text data would be helpful.

**Comment by shivdvaio** [comment]
fixed
