### ISSUE TITLE
Multiple line breaks not working

### ISSUE THREAD

**Issue by blbhargav** [flutter/flutter_markdown#325]
For multiple line breaks it is not working properly. It is taking on one line breaks.
For example `String exampleData="\n\nLine 1. \n\nLine2.\n\n\n\n### Heading \n\nLine3";
 Markdown(data: exampleData,)`. The output is 
![WhatsApp Image 2021-01-29 at 4 13 45 PM](https://user-images.githubusercontent.com/24856031/106270814-8d294880-6254-11eb-84df-c7c4b9276d73.jpeg)

I tried with line breaks "\<br />" but it didn't worked
`String exampleData="Line 1. \n\nLine2. <br /> <br /> \n\n### Heading \n\nLine3";`
![WhatsApp Image 2021-01-29 at 4 18 26 PM](https://user-images.githubusercontent.com/24856031/106270939-bcd85080-6254-11eb-8ad5-1e312bb43919.jpeg)

Am I missing something here?

**Comment by domesticmouse** [comment]
Please see @mjordan56's comment on issue https://github.com/flutter/flutter_markdown/issues/300#issuecomment-769581760 for a quick run down of how vertical spacing works.

The second thing to understand is that, unlike rendering Markdown in a web browser, the underlying renderer here is not a HTML renderer, but Flutter. Thus inserting random HTML into a markdown document won't achieve your expected outcome. Please see [the README](https://github.com/flutter/flutter_markdown/blob/master/README.md) for more detail.
