### ISSUE TITLE
Markdown inside Column throws

### ISSUE THREAD

**Issue by smartyboy** [flutter/flutter_markdown#348]
### Problem
When I put Markdown inside Column it throws. Probably I am doing something wrong, please enlighten me.

### Reproducing
Run the code. if Markdown is wrapped inside Column it throws. Try both.

```
import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    return Scaffold(
// code good
      body: Markdown(
          data: "# some markdown content \n some more data",
          styleSheetTheme: MarkdownStyleSheetBaseTheme.cupertino),
    );

// code throws
    return Scaffold(
      body: Column(children: [
        Markdown(
            data: "# some markdown content",
            styleSheetTheme: MarkdownStyleSheetBaseTheme.cupertino)
      ]),
    );
  }
}
```

### Environment
using flutter_markdown: ^0.6.0, same goes for null-safe version, thats where i stumbled on the issue.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.14.6 18G6032 darwin-x64, locale en-EE)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.3.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)
Tested on iOS simulator

### Console output for exception
Restarted application in 1,273ms.

════════ Exception caught by rendering library ═════════════════════════════════ The following assertion was thrown during performResize():
Vertical viewport was given unbounded height.

Viewports expand in the scrolling direction to fill their container. In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.

If this widget is always nested in a scrollable widget there is no need to use a viewport because there will always be enough vertical space for the children. In this case, consider using a Column instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size the height of the viewport to the sum of the heights of its children.

The relevant error-causing widget was
Markdown When the exception was thrown, this was the stack #0      RenderViewport.computeDryLayout.<anonymous closure> #1      RenderViewport.computeDryLayout #2      RenderBox.performResize #3      RenderObject.layout #4      RenderProxyBoxMixin.performLayout ... The following RenderObject was being processed when the exception was fired: RenderViewport NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE RenderObject: RenderViewport NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    needs compositing
    parentData: <none> (can use size)
    constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=Infinity)
    size: MISSING
    axisDirection: down
    crossAxisDirection: right
    offset: ScrollPositionWithSingleContext#61142(offset: 0.0, range: null..null, viewport: null, ScrollableState, AlwaysScrollableScrollPhysics -> BouncingScrollPhysics -> RangeMaintainingScrollPhysics, IdleScrollActivity#66d7c, ScrollDirection.idle)
    anchor: 0.0
    center child: RenderSliverPadding#80baa NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: paintOffset=Offset(0.0, 0.0)
        constraints: MISSING
        geometry: null
        padding: EdgeInsets.all(16.0)
        textDirection: ltr
        child: RenderSliverList#4a4b0 NEEDS-LAYOUT NEEDS-PAINT
            parentData: paintOffset=Offset(0.0, 0.0)
            constraints: MISSING
            geometry: null
            no children current live
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderViewport NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderViewport NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderIgnorePointer#661e4 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#9e465 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPointerListener#7caf4 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderSemanticsGestureHandler#0672c relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderPointerListener#7b72f relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: _RenderScrollSemantics#61c0c relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Column
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderFlex#630d5 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
RenderBox was not laid out: RenderViewport NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1940 pos 12: 'hasSize'

The relevant error-causing widget was
Markdown
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 566 libraries in 477ms.

**Comment by kevindqc** [comment]
Hi!

This issue is because of how Flutter handles layout. The important part of the error is at the beginning

> Vertical viewport was given unbounded height.
> 
> Viewports expand in the scrolling direction to fill their container. In this case, a vertical viewport was given an unlimited amount of vertical space in which to expand. This situation typically happens when a scrollable widget is nested inside another scrollable widget.
> 

Sure enough, `Markdown` contains a Scrollable widget.

To better understand what is going on, you should read https://flutter.dev/docs/development/ui/layout/constraints. It is vital to understand how the layout system works if you want to understand why you get those kind of errors. I'm still working on it lol.

In this case, I think it's because Column sizes itself to its children on the vertical axis. The only children is the Markdown, which contains a ListView. ListView, by default for performance reason, doesn't size itself by it's children, see https://api.flutter.dev/flutter/widgets/ScrollView/shrinkWrap.html

So you have two options:
1. You can use `MarkdownBody` instead, which doesn't contain the ListView. You'll have to handle padding and scrolling yourself .
2. You can pass `shrinkWrap: true` to your `Markdown` widget, which will get passed all the way to the `ListView` inside. That means the `ListView` will be only as tall as the markdown content, so the `Column` will only be as tall as the `ListView`, so no longer unbounded on the vertical axis, and the error is gone.

**Comment by smartyboy** [comment]
Thank you bro! Now its all clear.
