### ISSUE TITLE
Error during flutter packages get

### ISSUE THREAD

**Issue by dengelke** [flutter/flutter_markdown#4]
Getting a weird error when attempting to use this package

Running "flutter packages get" in flutter_markdown_experiment...
Package markdown has no versions that match ^0.11.0 derived from:
- flutter_markdown 0.0.9 depends on version ^0.11.0
pub get failed (1)

**Comment by eseidelGoogle** [comment]
It looks like markdown exists at that version:
https://pub.dartlang.org/packages/markdown

**Comment by dengelke** [comment]
There was an error with my pubspec.yaml - thanks @eseidelGoogle for the assistance
