### ISSUE TITLE
Add support for line breaks

### ISSUE THREAD

**Issue by KevinTheGray** [flutter/flutter_markdown#40]
Maybe I'm missing something, but I don't see a way to add line breaks where wanted.  A lot of Markdown supports this with the following rule: "To force a line return, place two empty spaces at the end of a line."  

I can get a maximum of one new line, after that, they seem to collapse.  I'd like to have something like
```
Hello
  
  
  
There are three lines of space above this
```

**Comment by DaveShuckerow** [comment]
Hi Kevin, thanks for noticing this!

This is reproducible at http://dart-lang.github.io/markdown/, so the root cause is the underlying Dart markdown library.

I suggest filing this issue there.  Link: https://github.com/dart-lang/markdown/issues

**Comment by KevinTheGray** [comment]
Ok thanks @DaveShuckerow, will do

**Comment by srawlins** [comment]
I don't see any empty spaces at the end of the line. Just empty lines.

**Comment by KevinTheGray** [comment]
@srawlins what are you referring to?  the example i posted?

**Comment by srawlins** [comment]
Sorry, better conversation over at dart-lang/markdown#214.

**Comment by KevinTheGray** [comment]
@DaveShuckerow it looks like the spec that http://dart-lang.github.io/markdown/ uses is called CommonMark, found here: http://spec.commonmark.org/0.28/#hard-line-breaks.  

Line breaks with this spec is done as in the following image:  

<img width="1614" alt="screen shot 2018-04-10 at 4 59 35 pm" src="https://user-images.githubusercontent.com/9346834/38583325-a40dddbe-3ce0-11e8-84b5-5ef5e4bacb5f.png">

You cant test that here: https://dart-lang.github.io/markdown/

I tested the result of `markdownToHtml` in the dart-lang markdown package, as follows

`String html = markdownToHtml('hello\\\n\\\n\\\n\\\nthere are three breaks above this line');`

which results in the following HTML
```
<p>hello<br />
<br />
<br />
<br />
there are three breaks above this line</p>
```

So I believe the dart-lang plugin in behaving as intended with the proper syntax.   However, the flutter plugin does not seem to be respect the \<br /> tags.  

So I believe this is a flutter-markdown plugin issue now that I've learned the proper syntax for CommonMark.

**Comment by xster** [comment]
cc @mit-mit :)

**Comment by mit-mit** [comment]
I'd be happy to review a PR for this!
