### ISSUE TITLE
Output includes HTML entities

### ISSUE THREAD

**Issue by hugovangalen** [flutter/flutter_markdown#42]
All output includes HTML entities. 

This makes sense when used in HTML pages -- but it doesn't look good in a Flutter app. Text widgets in Flutter do not render these HTML tags. For example: `Markdown & Flutter` ends up as `Markdown &amp; Flutter` and `Dart 1.0 < Dart 2.0` as `Dart 1.0 &lt; Dart 2.0`. This doesn't look good. 

I noticed that `flutter_markdown_test.dart` actually contains code to verify this behaviour. This doesn't make sense.

The expected behaviour, when Markdown includes a '&' or '<', should be that these are rendered correctly on the screen.

**Comment by westy92** [comment]
I'm having the same issue!
