### ISSUE TITLE
iframe content is not shown

### ISSUE THREAD

**Issue by czater** [flutter/flutter_markdown#48]
i have something like this: 
`<iframe allow="autoplay; encrypted-media" allowfullscreen="" scrolling="no" src="https://www.youtube.com/embed/xxxxxxx" width="560" height="400" frameborder="0"></iframe></p>`
which is not shown and I don't know why :/ Any help?

**Comment by asinel** [comment]
@czater It's widget for displaying text, not html content. As you can see in readme, it support only original markdown format: https://daringfireball.net/projects/markdown/
