### ISSUE TITLE
How to newline in long paragraph ?

### ISSUE THREAD

**Issue by lyquocnam** [flutter/flutter_markdown#51]
currently, i used: "  " and "<br/>" but both not work too.
How can i do that ?

**Comment by vagrantrobbie** [comment]
\n\n

**Comment by mjordan56** [comment]
Hi @lyquocnam. Your issue description is very terse but I'm assuming that you are trying to insert a hard line break inside a paragraph. The flutter_markdown package does support both the "two spaces at the end of a line of text" and the "backslash at the end of a line of text" to inject a hard line break. For example,
```
line one
line two
```
will get concatenated into a single line
```
line one line two
```
But, if you end the first line with either two spaces or a backslash character a hard line break will be inserted.
```
line one・・
line two
```
Produces
```
line one
line two
```
This is standard Markdown syntax and output behavior.

**Comment by domesticmouse** [comment]
Closing out
