### ISSUE TITLE
& to &amp; is BUG?

### ISSUE THREAD

**Issue by SinonGit** [flutter/flutter_markdown#58]
https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&h=350

to

https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&amp;cs=tinysrgb&amp;h=350

**Comment by KiraDiShira** [comment]
When will be available this fix? Thank you

**Comment by KagurazakaHanabi** [comment]
> Problem is caused by Dart's URI parsing.

It's caused by `markdown` package, dart-lang/markdown#272
