### ISSUE TITLE
How to set font size ?

### ISSUE THREAD

**Issue by jagdishjadeja** [flutter/flutter_markdown#64]
is there anyway to change font size ?

**Comment by jagdishjadeja** [comment]
I used TextSpan and problems solved

**Comment by yahiaboudah** [comment]
How can you use textspan to do that? 
I used some other trick. I modified the theme data of the flutter Material widget. That solved my problem. Take a look at the stylesheet class. It will provide you with a few clues.

**Comment by jagdishjadeja** [comment]
thats long way 
i wanted some sort

**Comment by patrickw7788** [comment]
For any new comer:
`
return Markdown(
      styleSheet: MarkdownStyleSheet.fromTheme(
          ThemeData(textTheme: TextTheme(body1: TextStyle(fontSize: 16)))),
      data: _aboutText,
      onTapLink: (link) async {
        if (await canLaunch(link)) {
          await launch(link);
        } else {
          throw 'Could not launch $link';
        }
      },
    );
`

**Comment by jagdishjadeja** [comment]
@patrickw7788 what if i want different font size ?
