### ISSUE TITLE
can we change color of text ?

### ISSUE THREAD

**Issue by jagdishjadeja** [flutter/flutter_markdown#67]
I want to highlight some text so i want to give some background color of it 
any idea on how can i do it ?

**Comment by yahiaboudah** [comment]
Have you found a workaround? If I can't do this, I'm thinking of switching back to the regular RichText flutter widget.. It's such a pain in the ass to create new TextSpans for every modification you want to make in your paragraph. This sucks.

**Comment by jagdishjadeja** [comment]
i used RichText and textspan in a loop so no pain and only gain

**Comment by ProgrammingLife** [comment]
@jagdishjadeja can you post an example?
