### ISSUE TITLE
pointy brackets("<" and ">") are not correctly shown in code blocks

### ISSUE THREAD

**Issue by X-Wei** [flutter/flutter_markdown#72]
![wrong](https://user-images.githubusercontent.com/1615196/48666382-e025e380-eac0-11e8-8553-b24be6a8ac04.png)

**Comment by alexander-manoharan** [comment]
+1 Is there a way to escape < or > symbols?

**Comment by X-Wei** [comment]
I have a quick and dirty [fix](https://github.com/X-Wei/flutter_markdown/commit/688fd9807d1389292e783bd9d8d60b115a0e282c#diff-a8fb296c7560f6c2752f5c2860dad595R142) for this, by simply replacing those symbols before they are rendered.

For a temp fix, you can use my version of flutter_markdown, just write this in pubspec.yaml:

```
flutter_markdown:
  git: git://github.com/X-Wei/flutter_markdown.git
```

**Comment by IchordeDionysos** [comment]
I did some investigation on this issue and it seems like the underlying `markdown` parser from the Dart team HTML escapes these symbols, despite a flag `escapeHtml: false` being set.

So I consider this a bug and opened a pull request over there
https://github.com/dart-lang/markdown/issues/261
