### ISSUE TITLE
Markdown underlined not working

### ISSUE THREAD

**Issue by VadPinchuk** [flutter/flutter_markdown#76]
Hi guys. 
I have found strange, that some markdowns working fine while other - not.
In our project I am using git repo reference to flutter_markdown.
Flutter version 1.1.1

~~Terms are crossed~~
++Terms are underlined++

This two are displayed like this. Let me know what is wrong with it 
Thanks in advance

<img width="348" alt="screen_shot_2019-01-10_at_4 45 54_pm" src="https://user-images.githubusercontent.com/9134717/50977141-4ac03200-14fa-11e9-9f24-78c855ba9d55.png">

**Comment by I-am-original** [comment]
Sorry @zoechi, but you are more active here. Can you ping someone who know this feature ?

**Comment by KagurazakaHanabi** [comment]
Markdown does not support underline, but you can create your own syntaxes.

**Comment by domesticmouse** [comment]
Fixed by #133
