### ISSUE TITLE
selected text copy

### ISSUE THREAD

**Issue by msterzhang** [flutter/flutter_markdown#88]
Hey, hello, thank you for your project. I met a problem in using it. If I want to copy text by long press, but it seems that there is no such function.

**Comment by GelaniNijraj** [comment]
Is there any update on this?

**Comment by IchordeDionysos** [comment]
Flutter 1.9 introduced a new [`SelectedableText` widget](https://api.flutter.dev/flutter/material/SelectableText-class.html) which may help you here.
